apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJwYXVsYWhha2VlbSIsInBhc3N3b3JkIjoiMTAwMjAwMzAwUXEiLCJlbWFpbCI6InBhdWxhLmhha2VlbUB5YWhvby5jb20iLCJhdXRoIjoiY0dGMWJHRm9ZV3RsWlcwNk1UQXdNakF3TXpBd1VYRT0ifX19
kind: Secret
metadata:
  creationTimestamp: null
  name: docker
type: kubernetes.io/dockerconfigjson
