name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: login dockerhub
      run: docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASS}}    
    - name: Build the Docker image
      run: |
       docker build . -t ${{ secrets.DOCKER_USER }}/wordpress_container_abi:latest
       # docker push ${{ secrets.DOCKER_USER }}/wordpress_container_abi:latest
    - name: Docker push
      run : docker push ${{ secrets.DOCKER_USER }}/wordpress_container_abi:latest
